import type { PrivateBrainPageData } from "./types";

export const mockPrivateBrainData: PrivateBrainPageData = {
  title: "Private Brain",
  subtitle: "Your memory. Your truth. Your evolution.",
  threadCount: 23,
  threads: [
    {
      id: "m1",
      title: "15lbs by July 15th",
      category: "goal",
      status: "active",
      updatedHoursAgo: 2,
      insightCount: 3,
    },
    {
      id: "m2",
      title: "Theresa",
      category: "personal",
      status: "active",
      updatedHoursAgo: 5,
      insightCount: 2,
    },
    {
      id: "m3",
      title: "Family Stuff",
      category: "family",
      status: "active",
      updatedHoursAgo: 8,
      insightCount: 4,
    },
    {
      id: "m4",
      title: "ACL recovery protocol",
      category: "health",
      status: "active",
      updatedHoursAgo: 12,
      insightCount: 6,
    },
    {
      id: "m5",
      title: "Magnesium research",
      category: "research",
      status: "active",
      updatedHoursAgo: 18,
      insightCount: 5,
    },
    {
      id: "m6",
      title: "Sleep routine",
      category: "sleep",
      status: "active",
      updatedHoursAgo: 24,
      insightCount: 3,
    },
    {
      id: "m7",
      title: "Morning mobility",
      category: "health",
      status: "active",
      updatedHoursAgo: 26,
      insightCount: 2,
    },
    {
      id: "m8",
      title: "Nutrition preferences",
      category: "goal",
      status: "active",
      updatedHoursAgo: 30,
      insightCount: 4,
    },
    {
      id: "m9",
      title: "Stress patterns",
      category: "personal",
      status: "active",
      updatedHoursAgo: 36,
      insightCount: 3,
    },
  ],
  insight: {
    headline: "Your brain is always learning.",
    body: "Memories evolve as you do — Auryn weaves context gently over time.",
  },
  tools: [
    { id: "organize", label: "Organize memories", description: "Group threads by theme" },
    { id: "preferences", label: "Memory preferences", description: "Control what Auryn remembers" },
    { id: "privacy", label: "Privacy controls", description: "Manage visibility and retention" },
    {
      id: "clear",
      label: "Clear history",
      description: "Remove selected memory threads",
      variant: "destructive",
    },
  ],
};
